//! Kiln's structured error type.
//!
//! Error messages are a product feature, not an afterthought. Every failure
//! Kiln reports should be able to answer four questions:
//!
//! 1. *What happened?*  — [`Error::summary`]
//! 2. *Why?*            — [`Error::reason`]
//! 3. *What did Kiln expect?* — [`Error::expected`]
//! 4. *What can I do?*  — [`Error::hints`]
//!
//! The type is deliberately hand-written rather than generated by `thiserror`:
//! the shape above is a contract with the user interface layer, and enum-per-crate
//! error types make that contract impossible to enforce. Rendering lives in
//! [`crate::ui`] so that colour and terminal capabilities stay out of the domain.

use std::error::Error as StdError;
use std::fmt;
use std::path::Path;

use crate::source::SourceLocation;

/// Broad category of a failure. Determines the process exit code.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ErrorKind {
    /// `kiln.toml` is missing a required field, malformed, or semantically invalid.
    Config,
    /// Something the user referred to does not exist (project, runtime, cache entry).
    NotFound,
    /// The request is well-formed but Kiln cannot satisfy it on this platform.
    Unsupported,
    /// A network operation failed.
    Network,
    /// A downloaded or cached artifact failed integrity verification.
    Verification,
    /// A filesystem operation failed.
    Io,
    /// The operation conflicts with existing state (e.g. a file that already exists).
    Conflict,
    /// The user interrupted the operation.
    Interrupted,
    /// A planned capability that this release does not implement yet.
    NotImplemented,
    /// A bug in Kiln.
    Internal,
}

impl ErrorKind {
    /// The process exit code Kiln uses for this category.
    ///
    /// These are stable and documented so CI systems can branch on them.
    pub const fn exit_code(self) -> u8 {
        match self {
            ErrorKind::Config => 2,
            ErrorKind::NotFound => 3,
            ErrorKind::Unsupported => 4,
            ErrorKind::Network => 5,
            ErrorKind::Verification => 6,
            ErrorKind::Io => 7,
            ErrorKind::Conflict => 8,
            ErrorKind::NotImplemented => 9,
            ErrorKind::Internal => 70,
            ErrorKind::Interrupted => 130,
        }
    }

    /// Stable machine-readable identifier, used by `--json` output.
    pub const fn as_str(self) -> &'static str {
        match self {
            ErrorKind::Config => "config",
            ErrorKind::NotFound => "not_found",
            ErrorKind::Unsupported => "unsupported",
            ErrorKind::Network => "network",
            ErrorKind::Verification => "verification",
            ErrorKind::Io => "io",
            ErrorKind::Conflict => "conflict",
            ErrorKind::Interrupted => "interrupted",
            ErrorKind::NotImplemented => "not_implemented",
            ErrorKind::Internal => "internal",
        }
    }
}

/// A single actionable suggestion attached to an error.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Hint {
    /// Prose advice.
    Text(String),
    /// A command the user can copy and run verbatim.
    Command(String),
}

impl Hint {
    /// The suggestion text, without any command decoration.
    pub fn text(&self) -> &str {
        match self {
            Hint::Text(s) | Hint::Command(s) => s,
        }
    }

    /// Whether this hint is a runnable command.
    pub fn is_command(&self) -> bool {
        matches!(self, Hint::Command(_))
    }
}

/// The error type returned by every fallible Kiln operation.
///
/// The payload is boxed. A structured diagnostic is a large value — several
/// strings, a source location, a list of hints — and it is on the cold path by
/// definition. Keeping [`Error`] pointer-sized means every `Result` in the
/// workspace stays cheap to return, and only the failing call pays for the
/// allocation.
#[derive(Debug)]
pub struct Error(Box<ErrorInner>);

#[derive(Debug)]
struct ErrorInner {
    kind: ErrorKind,
    summary: String,
    reason: Option<String>,
    expected: Option<String>,
    location: Option<SourceLocation>,
    hints: Vec<Hint>,
    source: Option<Box<dyn StdError + Send + Sync + 'static>>,
}

/// `Result` specialised to Kiln's [`Error`].
pub type Result<T, E = Error> = std::result::Result<T, E>;

impl Error {
    /// Construct an error of the given kind with a one-line summary.
    ///
    /// The summary should describe *what failed*, in the user's terms, without
    /// a trailing period — for example `"Could not read kiln.toml"`.
    pub fn new(kind: ErrorKind, summary: impl Into<String>) -> Self {
        Error(Box::new(ErrorInner {
            kind,
            summary: summary.into(),
            reason: None,
            expected: None,
            location: None,
            hints: Vec::new(),
            source: None,
        }))
    }

    /// A malformed or semantically invalid configuration.
    pub fn config(summary: impl Into<String>) -> Self {
        Error::new(ErrorKind::Config, summary)
    }

    /// Something the user referred to does not exist.
    pub fn not_found(summary: impl Into<String>) -> Self {
        Error::new(ErrorKind::NotFound, summary)
    }

    /// Well-formed request that Kiln cannot satisfy here.
    pub fn unsupported(summary: impl Into<String>) -> Self {
        Error::new(ErrorKind::Unsupported, summary)
    }

    /// Operation conflicts with state already on disk.
    pub fn conflict(summary: impl Into<String>) -> Self {
        Error::new(ErrorKind::Conflict, summary)
    }

    /// A bug in Kiln. Users should never be able to trigger these.
    pub fn internal(summary: impl Into<String>) -> Self {
        Error::new(ErrorKind::Internal, summary)
    }

    /// A filesystem failure, wrapping the underlying [`std::io::Error`].
    ///
    /// Always prefer this over a bare `?` on an io error: the path is the single
    /// most useful piece of information and `std::io::Error` does not carry it.
    pub fn io(summary: impl Into<String>, path: impl AsRef<Path>, source: std::io::Error) -> Self {
        Error::new(ErrorKind::Io, summary)
            .because(format!("{}: {}", path.as_ref().display(), source))
            .with_source(source)
    }

    /// A capability that is planned but not present in this release.
    ///
    /// Kiln never pretends to implement something it does not. Commands that are
    /// scheduled for a later phase fail loudly with this kind.
    pub fn not_implemented(what: impl fmt::Display, phase: impl fmt::Display) -> Self {
        Error::new(
            ErrorKind::NotImplemented,
            format!("{what} is not implemented in Kiln {}", crate::KILN_VERSION),
        )
        .because(format!(
            "This capability is scheduled for {phase}. Kiln reports unimplemented \
             features explicitly rather than silently doing something else."
        ))
        .hint("see the roadmap in README.md for the current phase order")
    }

    /// Explain *why* the operation failed.
    #[must_use]
    pub fn because(mut self, reason: impl Into<String>) -> Self {
        self.0.reason = Some(reason.into());
        self
    }

    /// Describe what Kiln expected instead. May span multiple lines.
    #[must_use]
    pub fn expected(mut self, expected: impl Into<String>) -> Self {
        self.0.expected = Some(expected.into());
        self
    }

    /// Attach the position in a source file that caused the error.
    #[must_use]
    pub fn at(mut self, location: SourceLocation) -> Self {
        self.0.location = Some(location);
        self
    }

    /// Attach prose advice.
    #[must_use]
    pub fn hint(mut self, hint: impl Into<String>) -> Self {
        self.0.hints.push(Hint::Text(hint.into()));
        self
    }

    /// Attach a command the user can run to make progress.
    #[must_use]
    pub fn command(mut self, command: impl Into<String>) -> Self {
        self.0.hints.push(Hint::Command(command.into()));
        self
    }

    /// Attach the underlying cause, for `-v` diagnostics.
    #[must_use]
    pub fn with_source(mut self, source: impl StdError + Send + Sync + 'static) -> Self {
        self.0.source = Some(Box::new(source));
        self
    }

    /// The failure category.
    pub fn kind(&self) -> ErrorKind {
        self.0.kind
    }

    /// One-line description of what failed.
    pub fn summary(&self) -> &str {
        &self.0.summary
    }

    /// Why it failed, if Kiln knows.
    pub fn reason(&self) -> Option<&str> {
        self.0.reason.as_deref()
    }

    /// What Kiln expected instead, if applicable.
    pub fn expectation(&self) -> Option<&str> {
        self.0.expected.as_deref()
    }

    /// Position in a source file, for configuration errors.
    pub fn location(&self) -> Option<&SourceLocation> {
        self.0.location.as_ref()
    }

    /// Actionable suggestions, in the order they should be presented.
    pub fn hints(&self) -> &[Hint] {
        &self.0.hints
    }

    /// The process exit code for this error.
    pub fn exit_code(&self) -> u8 {
        self.0.kind.exit_code()
    }
}

impl fmt::Display for Error {
    /// A single line, for logs. The full presentation lives in [`crate::ui::Ui::report`].
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0.summary)?;
        if let Some(reason) = &self.0.reason {
            write!(f, ": {reason}")?;
        }
        Ok(())
    }
}

impl StdError for Error {
    fn source(&self) -> Option<&(dyn StdError + 'static)> {
        self.0
            .source
            .as_deref()
            .map(|e| e as &(dyn StdError + 'static))
    }
}

// ---------------------------------------------------------------------------
// Carrying a structured error through serde
// ---------------------------------------------------------------------------
//
// Kiln validates configuration values inside their `Deserialize` impls, because
// that is what makes the TOML parser hand back the byte span of the offending
// token. The cost is that the failure has to travel as a flat string through
// `serde::de::Error::custom`. These two functions define that wire format, so
// the structure survives the trip and the renderer still gets its four sections.

/// Prefix marking a line of the "Expected" block.
const EXPECTED_PREFIX: &str = "> ";
/// Prefix marking a suggestion.
const HINT_PREFIX: &str = "! ";

/// An error decoded back out of a serde message.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct DecodedMessage {
    /// One-line description, suitable as a code-frame label.
    pub label: String,
    /// The "Expected" block, if the original error had one.
    pub expected: Option<String>,
    /// Suggestions, in their original order.
    pub hints: Vec<String>,
}

/// Flatten an error into a `serde::de::Error::custom` payload.
pub fn to_serde_message(error: &Error) -> String {
    let mut out = match error.reason() {
        Some(reason) => format!("{}: {reason}", error.summary()),
        None => error.summary().to_string(),
    };
    // The label must stay on one line; a stray newline would be read as a section.
    out = out.replace('\n', " ");

    if let Some(expected) = error.expectation() {
        for line in expected.lines() {
            out.push('\n');
            out.push_str(EXPECTED_PREFIX);
            out.push_str(line);
        }
    }
    for hint in error.hints() {
        out.push('\n');
        out.push_str(HINT_PREFIX);
        out.push_str(hint.text());
    }
    out
}

/// Recover the structure written by [`to_serde_message`].
///
/// Messages that did not come from Kiln — `serde`'s own "unknown field" text,
/// for instance — decode to a bare label, which is exactly right.
pub fn decode_serde_message(message: &str) -> DecodedMessage {
    let mut decoded = DecodedMessage::default();
    let mut expected: Vec<&str> = Vec::new();

    for (index, line) in message.lines().enumerate() {
        if index == 0 {
            decoded.label = line.trim().to_string();
        } else if let Some(rest) = line.strip_prefix(EXPECTED_PREFIX) {
            expected.push(rest);
        } else if let Some(rest) = line.strip_prefix(HINT_PREFIX) {
            decoded.hints.push(rest.to_string());
        } else if !line.trim().is_empty() {
            // Unrecognised continuation: keep it rather than dropping information.
            expected.push(line);
        }
    }

    if !expected.is_empty() {
        decoded.expected = Some(expected.join("\n"));
    }
    decoded
}

/// Adds path-aware context to `std::io` results.
pub trait IoResultExt<T> {
    /// Convert an io failure into a Kiln error that names the path involved.
    fn io_context(self, summary: impl Into<String>, path: impl AsRef<Path>) -> Result<T>;
}

impl<T> IoResultExt<T> for std::result::Result<T, std::io::Error> {
    fn io_context(self, summary: impl Into<String>, path: impl AsRef<Path>) -> Result<T> {
        self.map_err(|e| Error::io(summary, path, e))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exit_codes_are_distinct_and_stable() {
        let kinds = [
            ErrorKind::Config,
            ErrorKind::NotFound,
            ErrorKind::Unsupported,
            ErrorKind::Network,
            ErrorKind::Verification,
            ErrorKind::Io,
            ErrorKind::Conflict,
            ErrorKind::NotImplemented,
            ErrorKind::Internal,
            ErrorKind::Interrupted,
        ];
        let mut seen = Vec::new();
        for kind in kinds {
            let code = kind.exit_code();
            assert!(code != 0, "{kind:?} must not exit successfully");
            assert!(!seen.contains(&code), "duplicate exit code for {kind:?}");
            seen.push(code);
        }
        assert_eq!(ErrorKind::Config.exit_code(), 2);
        assert_eq!(ErrorKind::Interrupted.exit_code(), 130);
    }

    #[test]
    fn display_joins_summary_and_reason() {
        let err = Error::config("Invalid kiln.toml").because("runtime.node is empty");
        assert_eq!(err.to_string(), "Invalid kiln.toml: runtime.node is empty");
    }

    #[test]
    fn io_errors_carry_the_path() {
        let err = Error::io(
            "Could not read kiln.toml",
            "/tmp/does-not-exist/kiln.toml",
            std::io::Error::new(std::io::ErrorKind::NotFound, "no such file"),
        );
        assert_eq!(err.kind(), ErrorKind::Io);
        assert!(
            err.reason()
                .unwrap()
                .contains("/tmp/does-not-exist/kiln.toml")
        );
        assert!(err.source().is_some());
    }

    #[test]
    fn serde_round_trip_preserves_every_section() {
        let original = Error::config("unsupported version requirement `banana`")
            .because("it is not a version")
            .expected("an exact version    22.14.0\na major pin         22")
            .hint("write `latest` if you meant the newest release")
            .command("kiln doctor");

        let decoded = decode_serde_message(&to_serde_message(&original));

        assert_eq!(
            decoded.label,
            "unsupported version requirement `banana`: it is not a version"
        );
        assert_eq!(
            decoded.expected.as_deref(),
            Some("an exact version    22.14.0\na major pin         22")
        );
        assert_eq!(
            decoded.hints,
            [
                "write `latest` if you meant the newest release",
                "kiln doctor"
            ]
        );
    }

    #[test]
    fn serde_labels_never_span_multiple_lines() {
        let error = Error::config("bad value").because("first line\nsecond line");
        let decoded = decode_serde_message(&to_serde_message(&error));
        assert_eq!(decoded.label, "bad value: first line second line");
        assert!(decoded.expected.is_none());
    }

    #[test]
    fn foreign_serde_messages_decode_to_a_bare_label() {
        let decoded = decode_serde_message("unknown field `runtimes`, expected one of `project`");
        assert_eq!(
            decoded.label,
            "unknown field `runtimes`, expected one of `project`"
        );
        assert!(decoded.expected.is_none());
        assert!(decoded.hints.is_empty());
    }

    #[test]
    fn not_implemented_names_the_phase() {
        let err = Error::not_implemented("kiln install", "Phase 2 (runtime management)");
        assert_eq!(err.kind(), ErrorKind::NotImplemented);
        assert!(err.reason().unwrap().contains("Phase 2"));
    }
}
