//! Reading `sha256sum`-style checksum files.
//!
//! Both runtimes Kiln supports publish their digests this way, one line per
//! artifact:
//!
//! ```text
//! e9404633bc02a5162…  node-v22.14.0-darwin-arm64.tar.gz
//! ```
//!
//! Matching is on the **whole** filename, never a prefix or a suffix. A lookup
//! for `…darwin-arm64.tar.gz` must not be satisfied by the `…darwin-arm64.tar.xz`
//! line sitting directly above it, and a lookup for `python-3.13` must not match
//! `python-3.13.1`. This is the step that decides which bytes Kiln will trust,
//! so a near-miss has to be a miss.

use kiln_core::{Digest, HashAlgorithm};

/// The digest listed for `filename`, if the file names it.
pub fn find(document: &str, filename: &str) -> Option<Digest> {
    entries(document)
        .find(|(name, _)| *name == filename)
        .map(|(_, digest)| digest)
}

/// Every `(filename, digest)` pair in the document.
///
/// Lines that are blank, commented, or not shaped like a checksum entry are
/// skipped: these files sometimes carry a header, and one odd line should not
/// discard the rest.
pub fn entries(document: &str) -> impl Iterator<Item = (&str, Digest)> {
    document.lines().filter_map(|line| {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            return None;
        }

        let (hex, rest) = line.split_once(char::is_whitespace)?;
        // GNU coreutils writes `*name` for binary mode.
        let name = rest.trim_start().trim_start_matches('*').trim();
        if name.is_empty() {
            return None;
        }

        let digest = Digest::parse(&format!("{}:{hex}", HashAlgorithm::Sha256)).ok()?;
        Some((name, digest))
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    const NODE_SUMS: &str = "\
e9404633bc02a5162c5c573b1e2490f5fb44648345d64a958b17e325729a5e42  node-v22.14.0-darwin-arm64.tar.gz
4e845cb71b4e897289312743b2e31c405a8a48720655404d82a4dce23fc43527  node-v22.14.0-darwin-arm64.tar.xz
9d942932535988091034dc94cc5f42b6dc8784d6366df3a36c4c9ccb3996f0c2  node-v22.14.0-linux-x64.tar.gz
";

    #[test]
    fn finds_a_digest_by_its_exact_filename() {
        let digest = find(NODE_SUMS, "node-v22.14.0-linux-x64.tar.gz").unwrap();
        assert_eq!(
            digest.hex(),
            "9d942932535988091034dc94cc5f42b6dc8784d6366df3a36c4c9ccb3996f0c2"
        );
    }

    #[test]
    fn a_different_extension_is_a_different_artifact() {
        // The two lines differ only after the last dot; picking the wrong one
        // would mean verifying a gzip tarball against an xz digest.
        let gz = find(NODE_SUMS, "node-v22.14.0-darwin-arm64.tar.gz").unwrap();
        let xz = find(NODE_SUMS, "node-v22.14.0-darwin-arm64.tar.xz").unwrap();
        assert_ne!(gz, xz);
    }

    #[test]
    fn prefixes_and_suffixes_do_not_match() {
        assert!(find(NODE_SUMS, "node-v22.14.0-darwin-arm64").is_none());
        assert!(find(NODE_SUMS, "arm64.tar.gz").is_none());
        assert!(find(NODE_SUMS, "").is_none());
    }

    #[test]
    fn missing_entries_are_none_rather_than_a_guess() {
        assert!(find(NODE_SUMS, "node-v99.0.0-darwin-arm64.tar.gz").is_none());
        assert!(find("", "anything").is_none());
    }

    #[test]
    fn binary_mode_markers_are_stripped() {
        let sums =
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 *artifact.tar.gz\n";
        assert!(find(sums, "artifact.tar.gz").is_some());
    }

    #[test]
    fn junk_lines_do_not_discard_the_rest() {
        let sums = format!("# generated by something\n\nnot a checksum line\n{NODE_SUMS}");
        assert_eq!(entries(&sums).count(), 3);
        assert!(find(&sums, "node-v22.14.0-linux-x64.tar.gz").is_some());
    }

    #[test]
    fn malformed_digests_are_skipped_not_trusted() {
        let sums = "\
zzzz  bad-hex.tar.gz
deadbeef  too-short.tar.gz
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  good.tar.gz
";
        assert!(find(sums, "bad-hex.tar.gz").is_none());
        assert!(find(sums, "too-short.tar.gz").is_none());
        assert!(find(sums, "good.tar.gz").is_some());
    }

    #[test]
    fn filenames_containing_spaces_are_read_whole() {
        let sums =
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  a name.tar.gz\n";
        assert!(find(sums, "a name.tar.gz").is_some());
    }

    #[test]
    fn a_large_document_is_searched_correctly() {
        // python-build-standalone ships one SHA256SUMS with ~850 entries.
        let mut document = String::new();
        for i in 0..900 {
            document.push_str(&format!(
                "{:064x}  cpython-3.13.{i}+20260807-aarch64-apple-darwin-install_only.tar.gz\n",
                i
            ));
        }
        assert_eq!(entries(&document).count(), 900);

        let target = "cpython-3.13.500+20260807-aarch64-apple-darwin-install_only.tar.gz";
        assert_eq!(
            find(&document, target).unwrap().hex(),
            format!("{:064x}", 500)
        );
    }
}
