[package]
name = "kiln-net"
description = "The only crate in Kiln allowed to talk to the network."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
kiln-core = { workspace = true }
tracing = { workspace = true }
ureq = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
